export * from './auth.service';
import { AuthService } from './auth.service';
export * from './avis.service';
import { AvisService } from './avis.service';
export * from './horaire.service';
import { HoraireService } from './horaire.service';
export * from './indisponibilite.service';
import { IndisponibiliteService } from './indisponibilite.service';
export * from './public.service';
import { PublicService } from './public.service';
export * from './rendezVous.service';
import { RendezVousService } from './rendezVous.service';
export * from './salon.service';
import { SalonService } from './salon.service';
export * from './service.service';
import { ServiceService } from './service.service';
export * from './utilisateur.service';
import { UtilisateurService } from './utilisateur.service';
export const APIS = [AuthService, AvisService, HoraireService, IndisponibiliteService, PublicService, RendezVousService, SalonService, ServiceService, UtilisateurService];
