/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HoraireOuvertureDTO { 
    jour: HoraireOuvertureDTO.JourEnum;
    /**
     * Heure d\'ouverture au format HH:MM (24h)
     */
    heureOuverture: string;
    /**
     * Heure de fermeture au format HH:MM (24h)
     */
    heureFermeture: string;
}
export namespace HoraireOuvertureDTO {
    export const JourEnum = {
        Lundi: 'LUNDI',
        Mardi: 'MARDI',
        Mercredi: 'MERCREDI',
        Jeudi: 'JEUDI',
        Vendredi: 'VENDREDI',
        Samedi: 'SAMEDI',
        Dimanche: 'DIMANCHE'
    } as const;
    export type JourEnum = typeof JourEnum[keyof typeof JourEnum];
}


