/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModifierStatutSalonDTO { 
    statut: ModifierStatutSalonDTO.StatutEnum;
}
export namespace ModifierStatutSalonDTO {
    export const StatutEnum = {
        EnAttente: 'EN_ATTENTE',
        Valide: 'VALIDE',
        Accepte: 'ACCEPTE'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
}


