/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RendezVousCreateDTO { 
    date?: string;
    heure?: string;
    description?: string;
    nomClient?: string;
    emailClient?: string;
    telephoneClient?: string;
    serviceId?: number;
}

