/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RendezVousDetail { 
    date?: string;
    heure?: string;
    description?: string;
    nomclient?: string;
    emailClient?: string;
    telephoneClient?: string;
    serviceNom?: string;
    servicePrix?: number;
    serviceDuree?: number;
    statut?: RendezVousDetail.StatutEnum;
}
export namespace RendezVousDetail {
    export const StatutEnum = {
        EnAttente: 'EN_ATTENTE',
        Confirme: 'CONFIRME',
        Annule: 'ANNULE',
        Termine: 'TERMINE'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
}


