/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RendezVousDTO { 
    id?: string;
    date?: string;
    heure?: string;
    description?: string;
    nomclient?: string;
    emailClient?: string;
    telephoneClient?: string;
    serviceNom?: string;
}

