/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RendezVousDTO { 
    date?: string;
    heure?: string;
    description?: string;
    nomclient?: string;
    emailClient?: string;
    telephoneClient?: string;
    statut?: RendezVousDTO.StatutEnum;
}
export namespace RendezVousDTO {
    export const StatutEnum = {
        EnAttente: 'EN_ATTENTE',
        Confirme: 'CONFIRME',
        Annule: 'ANNULE',
        Termine: 'TERMINE'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
}


