/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalonDTO { 
    id?: number;
    nom?: string;
    adresse?: string;
    latitude?: number;
    longitude?: number;
    imageProfil?: string;
    categorie?: string;
    statutOuverture?: SalonDTO.StatutOuvertureEnum;
}
export namespace SalonDTO {
    export const StatutOuvertureEnum = {
        Ouvert: 'OUVERT',
        Ferme: 'FERME'
    } as const;
    export type StatutOuvertureEnum = typeof StatutOuvertureEnum[keyof typeof StatutOuvertureEnum];
}


