/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalonInscriptionDTO { 
    nomSalon?: string;
    email?: string;
    motDePasse?: string;
    categorie?: SalonInscriptionDTO.CategorieEnum;
}
export namespace SalonInscriptionDTO {
    export const CategorieEnum = {
        Femme: 'FEMME',
        Homme: 'HOMME',
        FemmeEtHomme: 'FEMME_ET_HOMME'
    } as const;
    export type CategorieEnum = typeof CategorieEnum[keyof typeof CategorieEnum];
}


