/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HoraireOuvertureDTO } from './horaireOuvertureDTO';
import { ServiceDTO } from './serviceDTO';


export interface SalonDetail { 
    nom?: string;
    adresse?: string;
    description?: string;
    latitude?: number;
    longitude?: number;
    images?: string;
    categorie?: string;
    horaireOuverture?: Array<HoraireOuvertureDTO>;
    service?: Array<ServiceDTO>;
}

