/**
 * SalonMaster API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageDTO } from './imageDTO';


export interface ServiceDTO { 
    id?: number;
    nom?: string;
    description?: string;
    prix?: number;
    duree?: number;
    images?: Array<ImageDTO>;
}

